# Use the Terraform image as the base
FROM hashicorp/terraform:1.5.5

# Install Python and related tools
RUN apk add --no-cache \
    python3 \
    python3-dev \
    py3-pip \
    build-base \
    curl \
    unzip \
    zip \
    bash \
    git

# Upgrade pip and install Python dependencies
RUN pip install --no-cache-dir --upgrade pip

# Set working directory
WORKDIR /server

# Copy application files
COPY ./server /server

# Install application Python dependencies
RUN pip install --no-cache-dir -r /server/requirements.txt

ENV FLASK_ENV=development

# Expose the application port
EXPOSE 5000

# Reset entrypoint to allow running Python commands
ENTRYPOINT []

# Default command to run the Flask application
CMD ["python", "main.py"]

